### Create plot request
POST http://localhost:8080/requests/create
Content-Type: application/json

{
  "user": {
    "id": 1
  },
  "plot": {
    "id": 2,
    "plotName": "Plot 2",
    "available": true
  },
  "status": "PENDING"
}

### Get all requests
GET http://localhost:8080/requests/all

### Get requests by user
GET http://localhost:8080/requests/user/1

### Approve request
PUT http://localhost:8080/requests/2/approve

### Check available plots
GET http://localhost:8080/plots/available

### Create new plot
POST http://localhost:8080/plots/add
Content-Type: application/json

{
  "plotName": "Plot 4",
  "available": true
}

### Create request for Plot 4
POST http://localhost:8080/requests/create
Content-Type: application/json

{
  "user": {
    "id": 1
  },
  "plot": {
    "id": 4,
    "plotName": "Plot 4",
    "available": true
  },
  "status": "PENDING"
}

### Approve Plot 4 request
PUT http://localhost:8080/requests/3/approve

### Create request to reject
POST http://localhost:8080/requests/create
Content-Type: application/json

{
  "user": {
    "id": 1
  },
  "plot": {
    "id": 2,
    "plotName": "Plot 2",
    "available": true
  },
  "status": "PENDING"
}

### Reject request 4
PUT http://localhost:8080/requests/4/reject